version: '3.7'

x-deploy: &deploy
  stop_grace_period: 5s
  deploy:
    replicas: 2
    update_config:
      parallelism: 1
      failure_action: rollback

services:
  frontend-proxy:
    <<: *deploy
    image: nginx:alpine
    volumes:
      - ./conf/:/etc/nginx/conf.d/
      - ./certs/:/etc/nginx/certs/
      - ./includes/:/etc/nginx/includes/
      - type: bind
        source: /data/shareddata/
        target: /data/shareddata/
      - type: bind
        source: /data/mediawiki/
        target: /data/mediawiki/
    extra_hosts:
      - "donut.dwnet:172.16.0.1"
      - "eclair.dwnet:172.16.0.2"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"

  cache:
    stop_grace_period: 5s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
    image: varnish
    ports:
      # Not needed after php-fpm is in stack deploy
      - "6081:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /usr/local/var/varnish:exec

  citoid:
    <<: *deploy
    image: droidwiki/citoid
    depends_on:
      - zotero
    volumes:
      - ./citoid/config.yml:/bin/config.yml

  zotero:
    <<: *deploy
    image: zotero/translation-server

  parsoid:
    <<: *deploy
    image: droidwiki/parsoid
    volumes:
      - ./parsoid/config.yml:/bin/config.yaml

  restbase:
    <<: *deploy
    image: droidwiki/restbase
    depends_on:
      - citoid
      - parsoid
    ports:
      # Remove once php-fpm is in stack as well
      - "7231:7231"
    volumes:
      - ./restbase/config.yaml:/restbase/config.yaml
      - ./restbase/droidwiki.yaml:/restbase/projects/droidwiki.yaml
      - ./restbase/droidwiki_sys.yaml:/restbase/projects/sys/droidwiki.yaml
