version: '3.7'

services:
  frontend-proxy:
    stop_grace_period: 5s
    deploy:
      placement:
        constraints:
          - node.hostname == v22015112656329114
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
    image: nginx:alpine
    volumes:
      - ./conf/:/etc/nginx/conf.d/
      - ./certs/:/etc/nginx/certs/
      - ./includes/:/etc/nginx/includes/
      - type: bind
        source: /data/shareddata/www/
        target: /www/
      - type: bind
        source: /data/mediawiki/
        target: /mediawiki/
    extra_hosts:
      - "donut.dwnet:172.16.0.1"
      - "eclair.dwnet:172.16.0.2"
    ports:
      - "443:443"
      - "80:80"
