version: '3.7'

services:
  puppet:
    stop_grace_period: 5s
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1.00'
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
    image: droidwiki/puppetserver
    healthcheck:
      # For some reason, puppetserver never goes from satrting to running
      disable: true
    environment:
     - PUPPETSERVER_HOSTNAME=puppet
     - DNS_ALT_NAMES=puppet
     - CA_ENABLED=true
     - AUTOSIGN=true
     - USE_PUPPETDB=false
    ports:
     - "8140:8140"
    volumes:
     - /data/ha_volume/puppet/code/:/etc/puppetlabs/code/
     - /data/ha_volume/puppet/puppet/hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
     - /data/ha_volume/puppet/puppet/secure/:/etc/puppetlabs/puppet/secure/
     - /data/ha_volume/puppet/puppet/puppet.conf:/etc/puppetlabs/puppet/puppet.conf
