version: '3.7'

x-deploy: &deploy
  stop_grace_period: 5s
  deploy:
    replicas: 2
    update_config:
      parallelism: 1
      failure_action: rollback

services:
  frontend-proxy:
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
    image: droidwiki/nginx
    volumes:
      - ./nginx/certs/:/etc/nginx/certs/
      - type: bind
        source: /data/shareddata/
        target: /data/shareddata/
      - type: bind
        source: /data/ha_volume/go2tech.de/
        target: /data/ha_volume/go2tech.de/
      - type: bind
        source: /data/mediawiki/
        target: /data/mediawiki/
    extra_hosts:
      - "donut.dwnet:172.16.0.1"
      - "eclair.dwnet:172.16.0.2"
    ports:
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: ingress
        protocol: tcp
        published: 8080
        target: 8080

  php:
    <<: *deploy
    image: droidwiki/php-fpm
    user: 33:33
    volumes:
      - /data:/data

  jobrunner:
    stop_grace_period: 5s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
    image: droidwiki/jobrunner
    user: 33:33
    volumes:
      - /data:/data

  jobchron:
    stop_grace_period: 5s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
    image: droidwiki/jobchron
    user: 33:33
    volumes:
      - /data:/data

  cache:
    <<: *deploy
    image: droidwiki/varnish
    ports:
      # Not needed after php-fpm is in stack deploy
      - "6081:80"
    tmpfs:
      - /usr/local/var/varnish:exec

  memcached:
    stop_grace_period: 5s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
    image: memcached:alpine
    command: memcached -m 11410

  redis:
    image: redis:6.0.8-alpine
    volumes:
      - /data/ha_volume/redis:/data
    deploy:
      replicas: 1
    command: redis-server --appendonly yes

  thumbor:
    <<: *deploy
    image: minimalcompact/thumbor:6.7.5
    environment:
      - LOADER=thumbor.loaders.file_loader
      - FILE_LOADER_ROOT_PATH=/images
      - STORAGE=thumbor.storages.file_storage
      # Piloting, not saving generated files for now
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_FILE_STORAGE_ROOT_PATH=/images
      - RESULT_STORAGE_STORES_UNSAFE=True
    volumes:
      - /data/shareddata/mediawiki/images:/images

  citoid:
    <<: *deploy
    image: droidwiki/citoid
    depends_on:
      - zotero

  zotero:
    <<: *deploy
    image: zotero/translation-server:2.0.3

  parsoid:
    <<: *deploy
    image: droidwiki/parsoid

  restbase:
    <<: *deploy
    image: droidwiki/restbase
    depends_on:
      - citoid
      - parsoid
