version: '3.7'

services:
  frontend-proxy:
    build:
      context: nginx
    volumes:
      - ./nginx/certs/:/etc/nginx/certs/
      - type: bind
        source: /data/ha_volume/go2tech.de/
        target: /data/ha_volume/go2tech.de/
      - type: bind
        source: /data/ha_volume/cerberus-matches/data/
        target: /data/ha_volume/cerberus-matches/data/
    extra_hosts:
      - "donut.dwnet:172.16.0.1"
      - "eclair.dwnet:172.16.0.2"
    ports:
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: ingress
        protocol: tcp
        published: 8080
        target: 8080
