version: '3.7'

x-deploy: &deploy
  stop_grace_period: 5s
  deploy:
    replicas: 2
    update_config:
      parallelism: 1
      failure_action: rollback

networks:
  default:
    driver: overlay
    attachable: true

services:
  frontend-proxy:
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/frontend-proxy"
    image: droidwiki/nginx
    volumes:
      - ./nginx/certs/:/etc/nginx/certs/
      - type: bind
        source: /data/shareddata/
        target: /data/shareddata/
      - type: bind
        source: /data/ha_volume/go2tech.de/
        target: /data/ha_volume/go2tech.de/
      - type: bind
        source: /data/mediawiki/
        target: /data/mediawiki/
    extra_hosts:
      - "donut.dwnet:172.16.0.1"
      - "eclair.dwnet:172.16.0.2"
    networks:
      default:
    ports:
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: ingress
        protocol: tcp
        published: 8080
        target: 8080

  php:
    <<: *deploy
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/php"
    image: droidwiki/php-fpm:8.1
    user: 33:33
    networks:
      default:
    volumes:
      - /data:/data

  php-canary:
    <<: *deploy
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/php-canary"
    image: droidwiki/php-fpm:8.2
    user: 33:33
    networks:
      default:
    volumes:
      - /data:/data

  jobrunner:
    stop_grace_period: 5s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/jobrunner"
    image: droidwiki/jobrunner
    user: 33:33
    networks:
      default:
    volumes:
      - /data/mediawiki:/data/mediawiki
    environment:
      DB_NAMES: droidwikiwiki datawiki endroidwikiwiki opswiki armakothwiki

  cache:
    <<: *deploy
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/cache"
    image: droidwiki/varnish
    networks:
      default:
    tmpfs:
      - /usr/local/var/varnish:exec

  memcached:
    stop_grace_period: 5s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/memcached"
    networks:
      default:
    image: memcached:alpine
    command: memcached -m 11410

  redis:
    image: redis:6.0.8-alpine
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/redis"
    volumes:
      - /data/ha_volume/redis:/data
    deploy:
      replicas: 1
    networks:
      default:
    command: redis-server --appendonly yes

  thumbor:
    <<: *deploy
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/thumbor"
    image: minimalcompact/thumbor:6.7.5
    networks:
      default:
    environment:
      - LOADER=thumbor.loaders.file_loader
      - FILE_LOADER_ROOT_PATH=/images
      - STORAGE=thumbor.storages.file_storage
      # Piloting, not saving generated files for now
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_FILE_STORAGE_ROOT_PATH=/images
      - RESULT_STORAGE_STORES_UNSAFE=True
    volumes:
      - /data/shareddata/mediawiki/images:/images

  citoid:
    <<: *deploy
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/citoid"
    image: droidwiki/citoid
    networks:
      default:
    depends_on:
      - zotero

  zotero:
    <<: *deploy
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/zotero"
    image: zotero/translation-server:2.0.3
    networks:
      default:

  restbase:
    <<: *deploy
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "/docker/restbase"
    image: droidwiki/restbase
    networks:
      default:
    depends_on:
      - citoid
