resources:
- name: stack-config
  type: git
  check_every: 24h
  webhook_token: ((github.webhook_token))
  icon: github-circle
  source:
    uri: https://github.com/droidwiki/nginx-deploy.git
    paths:
      - web.yml

- name: nginx-src
  type: git
  check_every: 24h
  webhook_token: ((github.webhook_token))
  icon: github-circle
  source:
    uri: https://github.com/droidwiki/nginx-deploy.git
    paths:
      - nginx/*

- name: nginx-image
  type: docker-image
  check_every: 24h
  icon: docker
  source:
    username: ((docker.username))
    password: ((docker.access_token))
    repository: droidwiki/nginx

jobs:
  - name: nginx
    serial: true
    plan:
      - get: nginx-src
        trigger: true
      - put: nginx-image
        params:
          build: nginx-src/nginx

  - name: deploy
    serial: true
    plan:
      - in_parallel:
        - get: stack-config
          trigger: true
        - get: nginx-image
          passed: [nginx]
          trigger: true
          params:
            skip_download: true
      - task: deploy-stack
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: lgatica/openssh-client
              tag: latest
          inputs:
            - name: stack-config
          run:
            path: sh
            args:
              - -ec
              - |
                echo "((deployment.private_key))" > /tmp/ssh-key
                chmod 600 /tmp/ssh-key
                eval `ssh-agent -s`
                ssh-add /tmp/ssh-key

                ssh -o StrictHostKeyChecking=no ((deployment.username))@((docker.manager_host)) \
                  "sudo deploy-webserver" < stack-config/web.yml
